# Generated by Django 5.2.1 on 2025-05-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohumedad',
            name='raw',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
